### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by D7A44** [N4rr34n6/TgUserDetails#3]
python3 TgUserDetails.py -u d7a_44 
  File "/root/Desktop/tele/TgUserDetails/TgUserDetails.py", line 29
    api_id = ******** 
             ^^
SyntaxError: invalid syntax

Why?

**Comment by N4rr34n6** [comment]
Hi, it looks like you forgot to replace `api_id = ********` with your own `api_id`. Python doesn’t understand that kind of trick. Remember, you need your own `api_id` from Telegram. You can get it by signing up at the Telegram Developers site. So make sure to do that before running the script. Good luck!
